import Phaser from 'phaser';
type P={x:number;y:number};
export class DrawingSystem{
 private points:P[]=[];private bodies:MatterJS.BodyType[]=[];private drawing=false;private locked=false;private g:Phaser.GameObjects.Graphics;private physicalG:Phaser.GameObjects.Graphics;used=0;onRelease?:()=>void;
 private readonly pointerDown=(p:Phaser.Input.Pointer)=>this.start(p);private readonly pointerMove=(p:Phaser.Input.Pointer)=>this.move(p);private readonly pointerUp=()=>this.finish();
 constructor(private scene:Phaser.Scene,public maxInk:number,private solids:Phaser.Geom.Rectangle[]){this.g=scene.add.graphics().setDepth(8);this.physicalG=scene.add.graphics().setDepth(7);scene.input.on('pointerdown',this.pointerDown);scene.input.on('pointermove',this.pointerMove);scene.input.on('pointerup',this.pointerUp)}
 private valid(x:number,y:number){return x>8&&x<382&&y>88&&y<790&&!this.solids.some(r=>Phaser.Geom.Rectangle.Contains(r,x,y))}
 private start(p:Phaser.Input.Pointer){if(this.locked||!this.valid(p.x,p.y))return;this.drawing=true;this.points=[{x:p.x,y:p.y}];this.used=0}
 private move(p:Phaser.Input.Pointer){if(!this.drawing)return;const q=this.points.at(-1)!;const dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d<9)return;if(this.used+d>this.maxInk||!this.valid(p.x,p.y)){if(this.used+d>this.maxInk)this.finish();return}this.points.push({x:p.x,y:p.y});this.used+=d;this.render()}
 private render(){this.g.clear().lineStyle(11,0x5148d9,1).beginPath().moveTo(this.points[0].x,this.points[0].y);for(let i=1;i<this.points.length;i++){const a=this.points[i-1],b=this.points[i];this.g.lineTo((a.x+b.x)/2,(a.y+b.y)/2)}this.g.lineTo(this.points.at(-1)!.x,this.points.at(-1)!.y).strokePath();this.g.lineStyle(3,0x8e87ff,.9).strokePath()}
 private finish(){if(!this.drawing)return;this.drawing=false;if(this.points.length<2){this.points=[];this.g.clear();return}this.locked=true;const lengths:number[]=[];for(let i=1;i<this.points.length;i++){const a=this.points[i-1],b=this.points[i],len=Math.hypot(b.x-a.x,b.y-a.y),ang=Math.atan2(b.y-a.y,b.x-a.x);const body=this.scene.matter.add.rectangle((a.x+b.x)/2,(a.y+b.y)/2,len+5,11,{angle:ang,label:'shield',friction:.9,restitution:.08,density:.004,chamfer:{radius:5}});this.bodies.push(body);lengths.push(len+5);if(i>1)this.scene.matter.add.constraint(this.bodies[i-2],body,0,.94,{pointA:{x:lengths[i-2]/2,y:0},pointB:{x:-(len+5)/2,y:0}})}this.g.clear();this.update();this.onRelease?.()}
 update(){if(!this.locked)return;this.physicalG.clear();for(const body of this.bodies){const vertices=(body.vertices||[]).map(v=>({x:v.x,y:v.y}));if(vertices.length)this.physicalG.fillStyle(0x5148d9).fillPoints(vertices,true).lineStyle(2,0x8e87ff).strokePoints(vertices,true)}}
 destroy(){this.scene.input.off('pointerdown',this.pointerDown);this.scene.input.off('pointermove',this.pointerMove);this.scene.input.off('pointerup',this.pointerUp);this.g.destroy();this.physicalG.destroy();this.bodies=[]}
}
