import Phaser from 'phaser'; import {COLORS,W,H} from '../config/constants'; import {getLevel} from '../levels'; import type {LevelData} from '../levels/types'; import {Dog} from '../entities/Dog'; import {Bee} from '../entities/Bee'; import {DrawingSystem} from '../systems/DrawingSystem'; import {GameHUD} from '../ui/GameHUD'; import {SaveManager} from '../systems/SaveManager'; import {audio} from '../systems/AudioManager';
export class GameScene extends Phaser.Scene{
 private dataDef!:LevelData;private dog!:Dog;private bees:Bee[]=[];private draw!:DrawingSystem;private hud!:GameHUD;private started=false;private ended=false;private paused=false;private pausedAt=0;private remaining=0;private startAt=0;private rockViews:{body:MatterJS.BodyType,g:Phaser.GameObjects.Graphics,r:number}[]=[];
 constructor(){super('Game')}
 init(data:{level?:number}){
  this.dataDef=getLevel(data.level||1);this.bees=[];this.rockViews=[];this.started=false;this.ended=false;this.paused=false;this.pausedAt=0;this.startAt=0;this.remaining=this.dataDef.survivalTime;
 }
 create(){this.matter.world.resume();this.cameras.main.setBackgroundColor(COLORS.sky);this.matter.world.setBounds(0,84,W,H-84,40,true,true,false);const solids:Phaser.Geom.Rectangle[]=[];for(const p of [...this.dataDef.platforms,...(this.dataDef.walls||[])]){this.matter.add.rectangle(p.x,p.y,p.width,p.height,{isStatic:true,label:'solid'});solids.push(new Phaser.Geom.Rectangle(p.x-p.width/2,p.y-p.height/2,p.width,p.height));this.add.rectangle(p.x,p.y,p.width,p.height,COLORS.dirt).setStrokeStyle(5,COLORS.ground)}for(const s of this.dataDef.spikes||[])this.drawSpikes(s.x,s.y,s.width);for(const h of this.dataDef.hives)this.drawHive(h.x,h.y);for(const r of this.dataDef.rocks||[])this.addRock(r.x,r.y,r.r);this.dog=new Dog(this,this.dataDef.player.x,this.dataDef.player.y);this.draw=new DrawingSystem(this,this.dataDef.maxInk,solids);this.draw.onRelease=()=>this.beginAttack();this.hud=new GameHUD(this,this.dataDef.id,()=>this.scene.restart({level:this.dataDef.id}),()=>this.togglePause());if(this.dataDef.id===1&&!SaveManager.load().tutorialCompleted)this.tutorial();this.matter.world.on('collisionstart',(ev:Phaser.Physics.Matter.Events.CollisionStartEvent)=>{for(const pair of ev.pairs){const labels=[pair.bodyA.label,pair.bodyB.label];if(labels.includes('dog')&&(labels.includes('bee')||labels.includes('spike')||labels.includes('rock')))this.finish(false)}});this.events.once('shutdown',()=>this.cleanup())}
 private drawHive(x:number,y:number){const g=this.add.graphics().setDepth(2);g.fillStyle(0xe39a2e).fillEllipse(x,y,61,68);g.lineStyle(5,0xb96a25);for(let i=-2;i<=2;i++)g.lineBetween(x-24,y+i*10,x+24,y+i*10);g.fillStyle(0x5c3924).fillCircle(x,y+17,10)}
 private drawSpikes(x:number,y:number,width:number){const count=Math.floor(width/20),g=this.add.graphics();for(let i=0;i<count;i++){const px=x-width/2+i*20;g.fillStyle(0xe65d5d).fillTriangle(px,y+12,px+10,y-18,px+20,y+12)}this.matter.add.rectangle(x,y,width,28,{isStatic:true,isSensor:true,label:'spike'})}
 private addRock(x:number,y:number,r:number){const body=this.matter.add.circle(x,y,r,{label:'rock',density:.008,friction:.8,restitution:.1});this.rockViews.push({body,g:this.add.graphics().setDepth(3),r})}
 private tutorial(){const t=this.add.text(W/2,108,this.dataDef.hint!,{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#5148d9',backgroundColor:'#ffffff',padding:{x:12,y:8}}).setOrigin(.5).setDepth(25);const finger=this.add.text(80,570,'☝',{fontSize:'42px'}).setDepth(25);this.tweens.add({targets:finger,x:310,y:570,duration:1500,yoyo:true,repeat:2,onComplete:()=>{t.destroy();finger.destroy()}})}
 private beginAttack(){if(this.started)return;this.started=true;this.startAt=this.time.now;this.dog.setState('scared');audio.beep(280,.12,'sawtooth');for(const hive of this.dataDef.hives)for(let i=0;i<hive.beeCount;i++)this.time.delayedCall(i*hive.spawnDelay,()=>{if(!this.ended)this.bees.push(new Bee(this,hive.x+(Math.random()-.5)*20,hive.y+(Math.random()-.5)*18,hive.beeType))})}
 update(time:number){this.dog.update();this.draw.update();if(!this.paused)for(const b of this.bees)b.update(this.dog.body.position.x,this.dog.body.position.y,time,this.bees);for(const rv of this.rockViews){const p=rv.body.position;rv.g.clear().fillStyle(0x758093).fillCircle(p.x,p.y,rv.r).lineStyle(4,0x596474).strokeCircle(p.x,p.y,rv.r).fillStyle(0x929baa).fillCircle(p.x-rv.r*.25,p.y-rv.r*.2,rv.r*.18)}this.hud.updateInk(1-this.draw.used/this.dataDef.maxInk);if(this.started&&!this.ended&&!this.paused){this.remaining=this.dataDef.survivalTime-(time-this.startAt)/1000;this.hud.setTimer(this.remaining);if(this.remaining<=0)this.finish(true)}if(this.dog.body.position.y>H+40)this.finish(false)}
 private finish(win:boolean){if(this.ended)return;this.ended=true;this.matter.world.pause();this.dog.setState(win?'celebrating':'hurt');navigator.vibrate?.(win?[30,40,30]:80);if(win){const ratio=this.draw.used/this.dataDef.maxInk;const stars=ratio<=this.dataDef.starThresholds.threeStars?3:ratio<=this.dataDef.starThresholds.twoStars?2:1;SaveManager.complete(this.dataDef.id,stars);audio.beep(760,.2);this.time.delayedCall(350,()=>this.scene.start('Win',{level:this.dataDef.id,stars,used:Math.round(ratio*100)}))}else{audio.beep(130,.28,'square');this.scene.start('Lose',{level:this.dataDef.id})}}
 private togglePause(){if(this.ended)return;this.paused=!this.paused;if(this.paused){this.pausedAt=this.time.now;this.matter.world.pause();this.add.text(W/2,H/2,'PAUSED',{fontFamily:'Arial',fontSize:'36px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#253449',padding:{x:22,y:14}}).setOrigin(.5).setDepth(40).setName('pauseLabel')}else{this.startAt+=this.time.now-this.pausedAt;this.matter.world.resume();this.children.getByName('pauseLabel')?.destroy()}}
 private cleanup(){this.draw?.destroy();this.bees.forEach(b=>b.destroy());this.bees=[];this.rockViews=[];this.matter.world.removeAllListeners()}}
